[tool.poetry]
name = "agent"
version = "0.1.0"
description = "Templates for agentic choice."
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.88"

[tool.poetry.group.dev.dependencies]
cosmos-sdk = "ee"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
